
//  Utility file so that lsp can provide header paths in header files as well
#include "util/rtweekend.h"
#include "core/ray.h"
#include "hittable/hittable.h"
#include "hittable/hittable_list.h"
#include "hittable/sphere.h"
#include "math/color.h"
#include "math/vec3.h"
#include "core/camera.h"
#include "materials/material.h"
#include "materials/lambertian.h"
#include "materials/metal.h"
#include "materials/dielectric.h"
#include "scenes/scene.h"
#include "acceleration/bvh/aabb.h"
#include "acceleration/bvh/bvh.h"
#include "materials/textures/texture.h"
#include "materials/textures/solid_color.h"
#include "materials/textures/checker.h"
#include "external/stb/stb_image.h"
